const assert=require('node:assert/strict');
const test=require('node:test');
const Dev=require('../dev-tools.js');

test('개발자 모드는 dev=1 쿼리에서만 활성화된다',()=>{assert.equal(Dev.isDeveloperMode('?dev=1'),true);assert.equal(Dev.isDeveloperMode('?foo=1&dev=1'),true);assert.equal(Dev.isDeveloperMode('?dev=0'),false);assert.equal(Dev.isDeveloperMode('?debug=1'),false);assert.equal(Dev.isDeveloperMode(''),false)});
test('개발자 수치 입력은 허용 범위의 정수로 제한된다',()=>{assert.equal(Dev.clampInteger(4.6,0,5),5);assert.equal(Dev.clampInteger(-10,0,5),0);assert.equal(Dev.clampInteger(99,0,5),5);assert.equal(Dev.clampInteger('3',0,5),3);assert.equal(Dev.clampInteger('x',0,5,2),2)});
test('개발자 패널 1차 도구는 전투·상태·트럼프·카드 소환을 제공한다',()=>{const html=Dev.panelHtml();for(const marker of ['data-dev-battle="battle"','data-dev-battle="elite"','data-dev-battle="boss"','data-dev-stat="playerHp"','data-dev-stat="enemyHp"','data-dev-stat="chip"','data-dev-stat="shield"','data-dev-trump="S"','data-dev-card="deck"','data-dev-card="hand"'])assert.match(html,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('개발자 패널 2차 도구는 쇼다운 슬롯 구성·즉시 실행·계산 로그를 제공한다',()=>{const html=Dev.panelHtml();for(const marker of ['id="trickDevPlayerSlot1"','id="trickDevEnemySlot5"','data-dev-action="applyShowdownSlots"','data-dev-action="showdownNow"','id="trickDevShowdownLog"'])assert.match(html,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('개발자 패널 2차 확장은 세트 전적·상태·우세·리버·예약 강제를 제공한다',()=>{const html=Dev.panelHtml();for(const marker of ['id="trickDevSetResults"','data-dev-action="setStatus"','data-dev-advantage="player"','data-dev-advantage="enemy"','data-dev-river="auto"','data-dev-river="force"','data-dev-river="none"','data-dev-action="addReservation"'])assert.match(html,new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))});
test('세트 전적 문자열은 순서를 보존하고 승패무 및 연속 기록을 계산한다',()=>{assert.deepEqual(Dev.parseSetResults('W L D W W'),{ok:true,results:['player','enemy','draw','player','player']});assert.deepEqual(Dev.parseSetResults('승패무'),{ok:true,results:['player','enemy','draw']});assert.equal(Dev.parseSetResults('WWWWWW').ok,false);assert.equal(Dev.parseSetResults('WX').ok,false);assert.deepEqual(Dev.createSetHistoryFromResults(['player','player','enemy','player']),{trickResults:['player','player','enemy','player'],wins:3,losses:1,draws:0,lastResult:'player',winStreak:1,lossStreak:0})});
test('쇼다운 즉시 실행 준비 상태는 양쪽에 정확히 5장의 카드가 있을 때만 참이다',()=>{const slot=()=>({card:{suit:'S',rank:2}});assert.equal(Dev.showdownReady({slots:Array.from({length:5},slot),enemySlots:Array.from({length:5},slot)}),true);assert.equal(Dev.showdownReady({slots:Array.from({length:4},slot),enemySlots:Array.from({length:5},slot)}),false);assert.equal(Dev.showdownReady({slots:[slot(),slot(),null,slot(),slot()],enemySlots:Array.from({length:5},slot)}),false);assert.equal(Dev.showdownReady({ended:true,slots:Array.from({length:5},slot),enemySlots:Array.from({length:5},slot)}),false)});
test('상태 요약은 활성 스택만 표시한다',()=>{assert.equal(Dev.statusSummary({player:{shield:3,bleed:0,mark:{value:2}}},'player'),'shield3 mark2');assert.equal(Dev.statusSummary({enemy:{}},'enemy'),'없음')});
test('우세와 리버 표시 함수는 개발자 상태를 짧게 요약한다',()=>{assert.equal(Dev.currentAdvantageText({advantageState:{player:true,enemy:false}}),'나');assert.equal(Dev.currentAdvantageText({advantageState:{player:true,enemy:true}}),'양쪽');assert.equal(Dev.riverModeText({riverSnapshot:null}),'없음');assert.equal(Dev.riverModeText({riverSnapshot:{id:'dev:set:1:S:2'}}),'강제');assert.equal(Dev.riverModeText({riverSnapshot:{id:'set:1:S:2'}}),'자동')});
test('쇼다운 로그는 집계와 상세 효과 내역을 함께 표시한다',()=>{assert.equal(Dev.showdownTraceText(null),'아직 쇼다운 계산 로그 없음');const battle={showdownTrace:['족보: 페어 10','최종 위력: 16 : 5'],lastShowdownBreakdown:{player:{additives:[{label:'쇼다운 효과 · 테스트',value:3}],multipliers:[{label:'우세',bonus:.25}]},riverHit:{active:true,target:{name:'투페어'}}}};const text=Dev.showdownTraceText(battle);assert.match(text,/족보: 페어 10/);assert.match(text,/--- 상세 ---/);assert.match(text,/덧셈 · 쇼다운 효과 · 테스트: \+3/);assert.match(text,/배율 · 우세: \+25%/);assert.match(text,/리버 · 적중: 투페어 \+25%/)});
test('개발자 패널은 모바일 안전영역과 제한된 화면 폭을 사용한다',()=>{const css=Dev.panelCss();assert.match(css,/safe-area-inset-bottom/);assert.match(css,/width:min\(360px,calc\(100vw - 24px\)\)/);assert.match(css,/max-height:min\(70vh,620px\)/);assert.match(css,/grid-template-columns:22px minmax\(0,1fr\) minmax\(0,1fr\)/);assert.match(css,/\.devInline/)});
test('런타임 카드 정의가 없는 Node 환경에서도 카드 검색 API는 안전하다',()=>{assert.deepEqual(Dev.cardCandidates(),[]);assert.equal(Dev.findCandidate('없는 카드'),undefined)});
