const assert = require('node:assert/strict');
const test = require('node:test');
const { CARD_DEFINITION_BY_ID } = require('../cards.js');
const Effects = require('../effects.js');

function execute(id,trigger,overrides={}) {
  const calls=[];
  const card={suit:'S',rank:7,named:CARD_DEFINITION_BY_ID[id]};
  const context={card,enemyCard:{suit:'H',rank:8},history:Effects.newHistory(),effectiveRank:card.rank,slotIndex:0,slots:[],mods:{paint:false,plus:0,reverse:false,double:false},enemyForecast:0,lastNamed:null,random:()=>0,perform:(...args)=>calls.push(args),...overrides};
  Effects.run(trigger,card,context);return calls;
}
test('검은 탄환은 승리 피해 3과 쇼다운 위력 3을 적용한다',()=>{assert.deepEqual(execute('pack01.black_bullet','on_trick_win')[0].slice(0,2),['damage_enemy',3]);assert.equal(execute('pack01.black_bullet','on_showdown_score')[0][1],3)});
test('불사조는 승리 시 4 회복한다',()=>assert.equal(execute('pack01.phoenix','on_trick_win')[0][1],4));
test('골든 핸드는 트릭 승리 시 칩과 다음 트릭 손패를 준다',()=>{assert.deepEqual(execute('pack01.golden_hand','on_trick_win').map(call=>call.slice(0,2)),[['gain_chips',1],['grant_next_trick_hand_capacity',1]])});
test('로우 블러프는 적용 숫자 5 이하에서만 칩을 준다',()=>{assert.equal(execute('pack01.dirty_gambler','on_trick_win',{effectiveRank:5})[0][1],2);assert.equal(execute('pack01.dirty_gambler','on_trick_win',{effectiveRank:6}).length,0)});
test('예약 사격은 다음 승리 피해 예약을 만든다',()=>assert.deepEqual(execute('pack01.scheduled_delivery','on_play')[0].slice(0,2),['reserve_next_win_damage',6]));
test('유리 칼날은 출혈 3을 부여한다',()=>assert.equal(execute('pack01.sharp_glass','on_trick_win')[0][1],3));
test('비상 방패는 즉시 보호막 5를 준다',()=>assert.equal(execute('pack01.emergency_guard','on_play')[0][1],5));
test('재귀 함수는 직전 다른 네임드의 허용된 수치 효과 하나만 복사한다',()=>{assert.deepEqual(execute('pack01.recursive_function','on_trick_win',{lastNamed:{cardId:'pack01.black_bullet',action:'damage_enemy',value:3}})[0].slice(0,3),['damage_enemy',3,{copied:true}]);assert.equal(execute('pack01.recursive_function','on_trick_win',{lastNamed:{cardId:'pack01.recursive_function',action:'damage_enemy',value:3}}).length,0);assert.equal(execute('pack01.recursive_function','on_trick_win',{lastNamed:{cardId:'pack01.scheduled_delivery',action:'reserve_next_win_damage',value:6}}).length,0)});
test('예약 사격은 바로 다음 트릭에만 남고 패배나 무승부에도 사라진다',()=>{const reservations=[{type:'nextWinDamage',value:6,eligibleTrick:2}];const calls=[];assert.equal(Effects.resolveNextWinReservations(reservations,1,true,(...args)=>calls.push(args)).length,1);assert.deepEqual(Effects.resolveNextWinReservations(reservations,2,true,(...args)=>calls.push(args)),[]);assert.deepEqual(calls,[['damage_enemy',6]]);assert.deepEqual(Effects.resolveNextWinReservations(reservations,2,false,()=>assert.fail()),[])});
test('잔량 1%는 손에서 20% 소진 위험을 감수하고 5번 슬롯에서만 쇼다운 위력 12를 준다',()=>{let exhausted=0;const base={inHand:true,exhaust:()=>exhausted++};execute('pack01.battery_1pct','on_trick_end',{...base,random:()=>0.199});assert.equal(exhausted,1);execute('pack01.battery_1pct','on_trick_end',{...base,random:()=>0.2});execute('pack01.battery_1pct','on_trick_end',{...base,inHand:false,random:()=>0});assert.equal(exhausted,1);assert.equal(execute('pack01.battery_1pct','on_showdown_score',{slotIndex:3}).length,0);assert.equal(execute('pack01.battery_1pct','on_showdown_score',{slotIndex:4})[0][1],12)});
test('잠복 관측자는 3번 슬롯에서 예측만 +2 하고 쇼다운 위력은 올리지 않는다',()=>{assert.equal(execute('pack01.ambush_observer','after_card_slotted',{slotIndex:1}).length,0);assert.deepEqual(execute('pack01.ambush_observer','after_card_slotted',{slotIndex:2})[0].slice(0,2),['increase_enemy_forecast',2]);assert.equal(execute('pack01.ambush_observer','on_showdown_score',{slotIndex:2}).length,0)});
test('무승부 전용 trigger가 공통 effect registry에 등록되어 있다',()=>assert(Effects.TRIGGERS.includes('on_trick_draw')));
test('등록된 모든 효과는 trigger와 지속 범위를 명시하고 전부 구현 상태다',()=>{for(const card of Object.values(CARD_DEFINITION_BY_ID)){assert.equal(card.implemented,true);assert(card.effects.length);for(const effect of card.effects){assert(Effects.TRIGGERS.includes(effect.trigger));assert(['trick','set','battle','run'].includes(effect.duration))}}});
test('7.5-P 공통 효과 엔진은 구식 별도 우세 트리거와 우세 개수 조건을 지원하지 않는다',()=>{assert.equal(Effects.TRIGGERS.includes('on_showdown_advantage'),false);assert.equal(Effects.conditions.advantage_count_at_least,undefined);assert.equal(typeof Effects.conditions.player_has_advantage,'function');assert.equal(typeof Effects.conditions.enemy_has_advantage,'function')});

const { CARD_DEFINITIONS, GENERAL_EFFECT_CARD_DEFINITIONS, BASE_CARD_SLOTS, createBaseCardSlots, isPureCard, rewardCardIds } = require('../cards.js');
test('추가 효과 카드는 하나의 공용 카탈로그로 노출된다',()=>{const ids=CARD_DEFINITIONS.map(card=>card.id);assert(ids.length>0);assert.equal(new Set(ids).size,ids.length);assert.deepEqual(new Set(rewardCardIds()),new Set(ids));assert(ids.every(id=>CARD_DEFINITION_BY_ID[id]))});
test('알려진 옛 팩 선택 인자는 보상 풀을 분리하지 않는 호환 입력으로만 남고 알 수 없는 값은 거부한다',()=>{const all=rewardCardIds();assert.deepEqual(rewardCardIds(['pack01']),all);assert.deepEqual(rewardCardIds(['pack02']),all);assert.deepEqual(rewardCardIds([]),all);assert.throws(()=>rewardCardIds(['pack99']),RangeError)});
test('순수 기본 슬롯 52장과 공용 효과 카드 12장은 서로 독립적으로 존재한다',()=>{const cards=createBaseCardSlots();assert.equal(cards.length,52);assert.equal(cards.filter(isPureCard).length,52);assert.equal(GENERAL_EFFECT_CARD_DEFINITIONS.length,12);assert(cards.every(card=>card.named===null&&card.cardId===null&&card.effects.length===0));assert(GENERAL_EFFECT_CARD_DEFINITIONS.every(card=>card.id.startsWith('core.')&&card.effects.length>0))});
test('기본 트럼프의 52개 suit/rank 슬롯이 중복 없이 유지된다',()=>{assert.equal(BASE_CARD_SLOTS.length,52);assert.equal(new Set(BASE_CARD_SLOTS.map(card=>`${card.suit}${card.rank}`)).size,52);for(const suit of ['S','H','D','C'])assert.deepEqual(BASE_CARD_SLOTS.filter(card=>card.suit===suit).map(card=>card.rank),Array.from({length:13},(_,i)=>i+2))});
test('효과 카드 화면·덱·전투·보상은 동일 정의와 이미지를 참조한다',()=>{const rewards=new Set(rewardCardIds());for(const definition of CARD_DEFINITIONS){const deckCard={named:CARD_DEFINITION_BY_ID[definition.id],cardId:definition.id};const battleCard={...deckCard};assert.strictEqual(definition,CARD_DEFINITION_BY_ID[definition.id]);assert.strictEqual(deckCard.named,battleCard.named);assert.equal(deckCard.named.image,definition.image);assert(rewards.has(definition.id))}});
test('5번째 트릭의 다음 트릭 예약은 다음 세트 1트릭에서 처리된다',()=>{const reservations=[{type:'nextWinDamage',value:6,eligibleSet:2,eligibleTrick:1}];const calls=[];assert.equal(Effects.resolveNextWinReservations(reservations,{set:1,trick:5},true,(...x)=>calls.push(x)).length,1);assert.deepEqual(Effects.resolveNextWinReservations(reservations,{set:2,trick:1},true,(...x)=>calls.push(x)),[]);assert.deepEqual(calls,[['damage_enemy',6]])});
