const assert=require('node:assert/strict');
const test=require('node:test');
const Cards=require('../cards.js');
const Effects=require('../effects.js');

function execute(id,trigger,overrides={}){
  const calls=[];const definition=Cards.CARD_DEFINITION_BY_ID[id];
  const card={suit:definition.suit,rank:definition.rank,printedSuit:definition.suit,printedRank:definition.rank,named:definition,cardId:definition.id,effects:definition.effects.map(effect=>({...effect}))};
  const context={card,enemyCard:{suit:'H',rank:8},history:Effects.newHistory(),effectiveRank:card.rank,effectiveSuit:card.suit,slotIndex:0,slots:[],mods:{paint:false,plus:0,reverse:false,double:false},enemyForecast:0,lastNamed:null,random:()=>0,perform:(...args)=>calls.push(args),...overrides};
  Effects.run(trigger,card,context);return{calls,card,context};
}
const calls=(id,trigger,overrides)=>execute(id,trigger,overrides).calls;

test('검은 탄환은 승리 피해 4, 5번 슬롯이면 추가 피해 4를 적용한다',()=>{assert.deepEqual(calls('pack01.black_bullet','on_trick_win',{slotIndex:2}).map(x=>x.slice(0,2)),[['damage_enemy',4]]);assert.deepEqual(calls('pack01.black_bullet','on_trick_win',{slotIndex:4}).map(x=>x.slice(0,2)),[['damage_enemy',4],['damage_enemy',4]]);assert.equal(calls('pack01.black_bullet','on_showdown_score',{slotIndex:4}).length,0)});
test('불사조는 승리 시 4 회복하고 저체력은 추가 3 회복한다',()=>{assert.deepEqual(calls('pack01.phoenix','on_trick_win',{playerHp:4,playerMaxHp:10}).map(x=>x.slice(0,2)),[['heal_player',3],['heal_player',4]]);assert.deepEqual(calls('pack01.phoenix','on_trick_win',{playerHp:7,playerMaxHp:10}).map(x=>x.slice(0,2)),[['heal_player',4]])});
test('골든 핸드는 트릭 승리 시 칩과 다음 트릭 손패를 준다',()=>{assert.deepEqual(calls('pack01.golden_hand','on_trick_win').map(call=>call.slice(0,2)),[['gain_chips',1],['grant_next_trick_hand_capacity',1]])});
test('로우 블러프는 적용 숫자 5 이하에서만 칩을 준다',()=>{assert.equal(calls('pack01.dirty_gambler','on_trick_win',{effectiveRank:5})[0][1],2);assert.equal(calls('pack01.dirty_gambler','on_trick_win',{effectiveRank:6}).length,0)});
test('예약 사격은 다음 승리 피해 8 예약을 만든다',()=>assert.deepEqual(calls('pack01.scheduled_delivery','on_play')[0].slice(0,2),['reserve_next_win_damage',8]));
test('유리 칼날은 기존 출혈 여부에 따라 선행 피해 후 출혈을 적용한다',()=>{assert.deepEqual(calls('pack01.sharp_glass','on_trick_win',{battle:{statuses:{enemy:{bleed:2}}}}).map(x=>x.slice(0,2)),[['damage_enemy',3],['apply_enemy_bleed',3]]);assert.deepEqual(calls('pack01.sharp_glass','on_trick_win',{battle:{statuses:{enemy:{bleed:0}}}}).map(x=>x.slice(0,2)),[['apply_enemy_bleed',3]])});
test('비상 방패는 즉시 보호막 6, 쇼다운에 보호막이 남으면 위력 +6이다',()=>{assert.deepEqual(calls('pack01.emergency_guard','on_play',{battle:{statuses:{player:{shield:0}}}})[0].slice(0,2),['gain_shield',6]);assert.deepEqual(calls('pack01.emergency_guard','on_showdown_score',{battle:{statuses:{player:{shield:1}}}})[0].slice(0,2),['showdown_power',6]);assert.equal(calls('pack01.emergency_guard','on_showdown_score',{battle:{statuses:{player:{shield:0}}}}).length,0)});
test('재귀 함수는 직전 다른 네임드의 허용된 수치 효과 하나만 복사한다',()=>{assert.deepEqual(calls('pack01.recursive_function','on_trick_win',{lastNamed:{cardId:'pack01.black_bullet',action:'damage_enemy',value:4}})[0].slice(0,3),['damage_enemy',4,{copied:true}]);assert.equal(calls('pack01.recursive_function','on_trick_win',{lastNamed:{cardId:'pack01.recursive_function',action:'damage_enemy',value:3}}).length,0);assert.equal(calls('pack01.recursive_function','on_trick_win',{lastNamed:{cardId:'pack01.scheduled_delivery',action:'reserve_next_win_damage',value:8}}).length,0)});
test('예약 사격은 바로 다음 트릭에만 남고 패배나 무승부에도 사라진다',()=>{const reservations=[{type:'nextWinDamage',value:8,eligibleTrick:2}],result=[];assert.equal(Effects.resolveNextWinReservations(reservations,1,true,(...args)=>result.push(args)).length,1);assert.deepEqual(Effects.resolveNextWinReservations(reservations,2,true,(...args)=>result.push(args)),[]);assert.deepEqual(result,[['damage_enemy',8]]);assert.deepEqual(Effects.resolveNextWinReservations(reservations,2,false,()=>assert.fail()),[])});
test('잔량 1%는 손에서 20% 소진 위험을 감수하고 5번 슬롯에서만 쇼다운 위력 12를 준다',()=>{let exhausted=0;const base={inHand:true,exhaust:()=>exhausted++};calls('pack01.battery_1pct','on_trick_end',{...base,random:()=>0.199});assert.equal(exhausted,1);calls('pack01.battery_1pct','on_trick_end',{...base,random:()=>0.2});calls('pack01.battery_1pct','on_trick_end',{...base,inHand:false,random:()=>0});assert.equal(exhausted,1);assert.equal(calls('pack01.battery_1pct','on_showdown_score',{slotIndex:3}).length,0);assert.equal(calls('pack01.battery_1pct','on_showdown_score',{slotIndex:4})[0][1],12)});
test('잠복 관측자는 3번 슬롯에서 예측만 +2 하고 쇼다운 위력은 올리지 않는다',()=>{assert.equal(calls('pack01.ambush_observer','after_card_slotted',{slotIndex:1}).length,0);assert.deepEqual(calls('pack01.ambush_observer','after_card_slotted',{slotIndex:2})[0].slice(0,2),['increase_enemy_forecast',2]);assert.equal(calls('pack01.ambush_observer','on_showdown_score',{slotIndex:2}).length,0)});
test('무승부 전용 trigger와 새 범용 개성화 action/condition이 등록되어 있다',()=>{assert(Effects.TRIGGERS.includes('on_trick_draw'));for(const name of ['spend_chips','copy_previous_showdown_rank','snapshot_set_wins','showdown_power_from_memory_tiers','reserve_next_trick_comparison_reward'])assert(Effects.ACTIONS.includes(name),name);for(const name of ['printed_suit_is_trump','previous_showdown_slot_is_pure','player_hp_ratio_at_most','enemy_has_status','trick_is','river_miss_with_candidates','chips_at_least'])assert.equal(typeof Effects.conditions[name],'function',name)});
test('등록된 모든 효과는 trigger와 지속 범위를 명시하고 전부 구현 상태다',()=>{for(const card of Object.values(Cards.CARD_DEFINITION_BY_ID)){assert.equal(card.implemented,true);assert(card.effects.length);for(const effect of card.effects){assert(Effects.TRIGGERS.includes(effect.trigger));assert(['trick','set','battle','run'].includes(effect.duration));if(effect.action)assert(Effects.ACTIONS.includes(effect.action),`${card.id}:${effect.action}`);if(effect.condition)assert.equal(typeof Effects.conditions[effect.condition],'function',`${card.id}:${effect.condition}`)}}});
test('구식 자동 우세 개수 조건은 되살리지 않는다',()=>{assert.equal(Effects.conditions.advantage_count_at_least,undefined);assert.equal(typeof Effects.conditions.player_has_advantage,'function');assert.equal(typeof Effects.conditions.enemy_has_advantage,'function')});

test('추가 효과 카드는 하나의 공용 카탈로그로 노출된다',()=>{const ids=Cards.CARD_DEFINITIONS.map(card=>card.id);assert(ids.length>0);assert.equal(new Set(ids).size,ids.length);assert.deepEqual(new Set(Cards.rewardCardIds()),new Set(ids));assert(ids.every(id=>Cards.CARD_DEFINITION_BY_ID[id]))});
test('알려진 옛 팩 선택 인자는 보상 풀을 분리하지 않는 호환 입력으로만 남는다',()=>{const all=Cards.rewardCardIds();assert.deepEqual(Cards.rewardCardIds(['pack01']),all);assert.deepEqual(Cards.rewardCardIds(['pack02']),all);assert.deepEqual(Cards.rewardCardIds([]),all);assert.throws(()=>Cards.rewardCardIds(['pack99']),RangeError)});
test('순수 기본 슬롯 52장과 공용 효과 카드 12장은 서로 독립적이다',()=>{const cards=Cards.createBaseCardSlots();assert.equal(cards.length,52);assert.equal(cards.filter(Cards.isPureCard).length,52);assert.equal(Cards.GENERAL_EFFECT_CARD_DEFINITIONS.length,12);assert(cards.every(card=>card.named===null&&card.cardId===null&&card.effects.length===0));assert(Cards.GENERAL_EFFECT_CARD_DEFINITIONS.every(card=>card.id.startsWith('core.')&&card.effects.length>0))});
test('기본 트럼프 52개 suit/rank 슬롯은 중복 없이 유지된다',()=>{assert.equal(Cards.BASE_CARD_SLOTS.length,52);assert.equal(new Set(Cards.BASE_CARD_SLOTS.map(card=>`${card.suit}${card.rank}`)).size,52);for(const suit of ['S','H','D','C'])assert.deepEqual(Cards.BASE_CARD_SLOTS.filter(card=>card.suit===suit).map(card=>card.rank),Array.from({length:13},(_,i)=>i+2))});
test('효과 카드 화면·덱·전투·보상은 동일 정의를 참조한다',()=>{const rewards=new Set(Cards.rewardCardIds());for(const definition of Cards.CARD_DEFINITIONS){const deckCard={named:Cards.CARD_DEFINITION_BY_ID[definition.id],cardId:definition.id},battleCard={...deckCard};assert.strictEqual(definition,Cards.CARD_DEFINITION_BY_ID[definition.id]);assert.strictEqual(deckCard.named,battleCard.named);assert.equal(deckCard.named.image,definition.image);assert(rewards.has(definition.id))}});
test('5번째 트릭의 다음 트릭 예약은 다음 세트 1트릭에서 처리된다',()=>{const reservations=[{type:'nextWinDamage',value:8,eligibleSet:2,eligibleTrick:1}],result=[];assert.equal(Effects.resolveNextWinReservations(reservations,{set:1,trick:5},true,(...x)=>result.push(x)).length,1);assert.deepEqual(Effects.resolveNextWinReservations(reservations,{set:2,trick:1},true,(...x)=>result.push(x)),[]);assert.deepEqual(result,[['damage_enemy',8]])});
