const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Cards=require('../cards.js');
const Effects=require('../effects.js');
const Migrated=require('../migrated-tactic-cards.js');

function runCard(card,trigger,overrides={}){
  const calls=[];
  const context={card,enemyCard:{suit:'H',rank:8},history:Effects.newHistory(),mods:{paint:false,plus:0,reverse:false,double:false},printedRank:card.rank,printedSuit:card.suit,trickRank:card.rank,trickSuit:card.suit,effectiveRank:card.rank,effectiveSuit:card.suit,advantage:{mode:'explicit',playerActive:false,enemyActive:false,multiplier:1.25},setHistory:{wins:0,losses:0,draws:0},hand:[],slots:[],perform:(...args)=>calls.push(args),...overrides};
  const executed=Effects.run(trigger,card,context);return{calls,executed,context};
}

test('전술 출신 12종이 모두 일반 카드 정의로 활성화된다',()=>{assert.deepEqual(Migrated.validateDefinitions(),[]);assert.equal(Migrated.ACTIVE_CARD_DEFINITIONS.length,12);assert.equal(Migrated.DIRECT_CARD_DEFINITIONS.length,6);assert.deepEqual(Migrated.ACTIVE_CARD_DEFINITIONS.map(card=>card.legacyTacticId).sort(),['paint','plus2','draw','scout','double','barrier','burn','reverse','pureboost','clean','recolor','fakeid'].sort());assert(Migrated.ACTIVE_CARD_DEFINITIONS.every(card=>card.category==='general'&&card.implemented===true&&card.migrationStage))});
test('12장 인쇄 숫자/무늬는 기존 52장 규격 슬롯을 그대로 사용한다',()=>{const slots=Object.fromEntries(Migrated.ACTIVE_CARD_DEFINITIONS.map(card=>[card.legacyTacticId,`${card.suit}${card.rank}`]));assert.deepEqual(slots,{paint:'D4',plus2:'S3',draw:'C6',scout:'D9',double:'H2',barrier:'S6',burn:'C2',reverse:'H3',pureboost:'D5',clean:'S4',recolor:'C9',fakeid:'H10'})});
test('일반 효과 카드는 named gameplay alias 없이 definition/effects로 생성된다',()=>{for(const definition of Migrated.ACTIVE_CARD_DEFINITIONS){const card=Cards.createDefinitionCard(definition.id,{uid:`test-${definition.legacyTacticId}`});assert.equal(card.named,null,definition.id);assert.equal(card.definition.id,definition.id);assert.equal(card.name,definition.name);assert.equal(card.effects.length,definition.effects.length);assert(card.effects.length>0,definition.id)}});
test('드로우는 다음 트릭 한정 손패 증가 액션을 실행한다',()=>{const card=Cards.createDefinitionCard('core.draw',{uid:'draw'}),result=runCard(card,'on_play');assert.equal(result.executed,1);assert.deepEqual(result.calls[0].slice(0,2),['grant_next_trick_hand_capacity',1])});
test('정찰은 정확 공개와 다음 트릭 비교 보상 예약을 둘 다 실행한다',()=>{const card=Cards.createDefinitionCard('core.scout',{uid:'scout'}),battle={setIndex:1,trick:2,reservations:[]},result=runCard(card,'on_play',{battle});assert.equal(result.executed,2);assert.equal(result.calls[0][0],'reveal_next_enemy_card');assert.equal(battle.reservations.length,1);assert.equal(battle.reservations[0].eligibleTrick,3);assert.equal(battle.reservations[0].action,'gain_chips')});
test('더블다운은 칩이 있을 때만 소비하고 적용 숫자 +5를 연다',()=>{const card=Cards.createDefinitionCard('core.double',{uid:'double'}),battle={setIndex:1,trick:1,chip:1,history:Effects.newHistory(),chipEconomy:{balance:1,lastBaseWinKey:null,lastExchangeKey:null,exchanges:0}},result=runCard(card,'on_play',{battle,history:battle.history});assert.equal(result.executed,2);assert.equal(battle.chip,0);assert.equal(battle.history.chipsSpent,1);assert.deepEqual(result.calls[0].slice(0,2),['increase_next_trick_rank',5])});
test('패갈이는 다른 손패 1장을 요구하고 버림→칩→드로우 순서로 실행한다',()=>{const card=Cards.createDefinitionCard('core.burn',{uid:'burn'});assert.deepEqual(card.definition.targeting,{zone:'hand',count:1,excludeSelf:true});const result=runCard(card,'on_play',{secondaryTargetCard:{uid:'other',suit:'H',rank:7}});assert.equal(result.executed,3);assert.deepEqual(result.calls.map(call=>call.slice(0,2)),[['discard_secondary_target',undefined],['gain_chips',1],['draw_cards',1]])});
test('정공법은 바로 이전 쇼다운 슬롯이 순수 카드일 때만 자기 트릭 숫자 +4다',()=>{const card=Cards.createDefinitionCard('core.pureboost',{uid:'pureboost'}),pure=Cards.createCardRecord({suit:'C',rank:8}),effect=Cards.createDefinitionCard('core.plus2',{uid:'plus2'});const active=runCard(card,'on_play',{slots:[{card:pure}],slotIndex:1});const blocked=runCard(card,'on_play',{slots:[{card:effect}],slotIndex:1});const first=runCard(card,'on_play',{slots:[],slotIndex:0});assert.equal(active.executed,1);assert.deepEqual(active.calls[0].slice(0,2),['increase_next_trick_rank',4]);assert.equal(blocked.executed,0);assert.equal(first.executed,0)});
test('무첨가는 쇼다운 슬롯에 다른 순수 카드가 있을 때 트릭 승리 칩 +2를 준다',()=>{const card=Cards.createDefinitionCard('core.clean',{uid:'clean'}),pure=Cards.createCardRecord({suit:'C',rank:8}),effect=Cards.createDefinitionCard('core.plus2',{uid:'plus2'});const active=runCard(card,'on_trick_win',{slots:[{card:pure},{card}]});const blocked=runCard(card,'on_trick_win',{slots:[{card:effect},{card}]});assert.equal(active.executed,1);assert.deepEqual(active.calls[0].slice(0,2),['gain_chips',2]);assert.equal(blocked.executed,0)});
test('가짜 신분증은 2~5번 슬롯에서 바로 이전 쇼다운 숫자를 복사한다',()=>{const card=Cards.createDefinitionCard('core.fakeid',{uid:'fake'}),previous=Cards.createCardRecord({suit:'C',rank:8});previous.showdownRank=11;const active=runCard(card,'on_play',{slots:[{card:previous},{card}],slotIndex:1});assert.equal(active.executed,1);assert.equal(card.showdownRank,11);assert.equal(card.showdownSuit,undefined)});
test('일반 효과 카드와 추가 효과 카드는 독립 정의이며 추가 효과 보상은 하나의 공용 풀이다',()=>{assert.equal(Cards.GENERAL_EFFECT_CARD_DEFINITIONS.length,12);const effectIds=Cards.CARD_DEFINITIONS.map(card=>card.id);const generalIds=new Set(Cards.GENERAL_EFFECT_CARD_DEFINITIONS.map(card=>card.id));assert(effectIds.length>0);assert.equal(new Set(effectIds).size,effectIds.length);assert(effectIds.every(id=>!generalIds.has(id)));const rewards=Cards.rewardCardIds();assert.equal(rewards.length,effectIds.length);assert.deepEqual(new Set(rewards),new Set(effectIds));assert.deepEqual(Cards.rewardCardIds(['pack01']),rewards);assert.deepEqual(Cards.rewardCardIds(['pack02']),rewards)});
test('카드 설명에는 구식 복수 우세 무늬 조건이 남지 않는다',()=>{const source=fs.readFileSync(path.join(__dirname,'..','migrated-tactic-cards.js'),'utf8');assert.doesNotMatch(source,/advantage_count_at_least|playerAdvantageCount|우세 무늬/)});
