const test=require('node:test');
const assert=require('node:assert/strict');
const Migration=require('../tactic-card-migration.js');
const Migrated=require('../migrated-tactic-cards.js');
const CardEffects=require('../effects.js');
const Cards=require('../cards.js');

test('기존 12종 카드 이관 계획은 빠짐없이 유지된다',()=>{const planned=Migration.PLAN.map(entry=>entry.legacyId).sort(),migrated=Migrated.ACTIVE_CARD_DEFINITIONS.map(card=>card.legacyTacticId).sort();assert.deepEqual(planned,migrated);assert.equal(Migration.PLAN.length,12);assert.deepEqual(Migration.validatePlan(),[])});
test('후보 인쇄 슬롯은 12장 모두 유효하고 서로 겹치지 않는다',()=>{const slots=Migration.PLAN.map(entry=>`${entry.printedSuit}:${entry.printedRank}`);assert.equal(new Set(slots).size,12);for(const entry of Migration.PLAN){assert.ok(Migration.SUITS.includes(entry.printedSuit));assert.ok(Migration.RANKS.includes(entry.printedRank))}});
test('후보는 네 수트에 3장씩 균등 배치한다',()=>{const counts=Object.fromEntries(Migration.SUITS.map(suit=>[suit,0]));Migration.PLAN.forEach(entry=>counts[entry.printedSuit]++);assert.deepEqual(counts,{S:3,H:3,D:3,C:3})});
test('후보 인쇄 슬롯은 현재 pack01 네임드 슬롯과 겹치지 않는다',()=>{const namedSlots=new Set(Cards.CARD_DEFINITIONS.map(card=>`${card.suit}:${card.rank}`)),collisions=Migration.PLAN.filter(entry=>namedSlots.has(`${entry.printedSuit}:${entry.printedRank}`));assert.deepEqual(collisions,[])});
test('기존 직접 이관 6종 분류는 유지한다',()=>{assert.deepEqual([...Migration.DIRECT_IDS].sort(),['barrier','fakeid','paint','plus2','recolor','reverse'].sort());for(const id of Migration.DIRECT_IDS)assert.equal(Migration.BY_ID[id].activationStage,'3-1')});
test('7.5-P에서 기존 12종이 모두 최신 일반 카드 효과 정의를 가진다',()=>{assert.equal(Migration.RUNTIME_ACTIVE,true);assert.equal(Migration.SUPPORT_STAGE,'7.5-P');assert.equal(Migration.ACTIVATION_STAGE,'7.5-P');assert.equal(Migration.ACTIVE_IDS.length,12);assert.deepEqual(Migration.BLOCKED_IDS,[]);for(const id of Migration.ACTIVE_IDS){const entry=Migration.BY_ID[id];assert.ok(entry.proposedEffects.length>0,`${id}: proposedEffects`);assert.deepEqual(Migration.unsupportedRequirements(entry),[],`${id}: requirements`);for(const effect of entry.proposedEffects){assert.ok(effect.trigger,`${id}: trigger`);assert.ok(effect.duration,`${id}: duration`);assert.ok(CardEffects.TRIGGERS.includes(effect.trigger),`${id}: known trigger`);assert.ok(CardEffects.ACTIONS.includes(effect.action),`${id}: known action`);if(effect.condition)assert.equal(typeof CardEffects.conditions[effect.condition],'function',`${id}: known condition`)}}});
test('일반 카드 새 이름을 유지하고 드로우 이름은 바꾸지 않는다',()=>{const names=Object.fromEntries(Migration.PLAN.map(entry=>[entry.legacyId,entry.name]));assert.deepEqual(names,{paint:'트럼프 페인트',plus2:'랭크 부스트',draw:'드로우',scout:'정찰',double:'더블다운',barrier:'세이프가드',burn:'패갈이',reverse:'리버스',pureboost:'정공법',clean:'무첨가',recolor:'재도색',fakeid:'가짜 신분증'})});
test('드로우/패갈이/정찰은 기존 지원 액션을 계속 사용한다',()=>{assert.deepEqual(Migration.BY_ID.draw.proposedEffects,[{trigger:'on_play',action:'grant_next_trick_hand_capacity',value:1,duration:'trick'}]);assert.deepEqual(Migration.BY_ID.scout.proposedEffects,[{trigger:'on_play',action:'reveal_next_enemy_card',duration:'trick'}]);assert.deepEqual(Migration.BY_ID.burn.proposedEffects.map(effect=>effect.action),['discard_secondary_target','gain_chips','draw_cards']);assert.deepEqual(Migration.BY_ID.burn.targeting,{zone:'hand',count:1,excludeSelf:true})});
test('트럼프 페인트는 트럼프화와 숫자 +1, 세이프가드는 패배 시 추가 보호막을 사용한다',()=>{assert.deepEqual(Migration.BY_ID.paint.proposedEffects,[{trigger:'on_play',action:'set_next_trick_suit_to_trump',duration:'trick'},{trigger:'on_play',action:'increase_next_trick_rank',value:1,duration:'trick'}]);assert.deepEqual(Migration.BY_ID.barrier.proposedEffects,[{trigger:'on_play',action:'gain_shield',value:3,duration:'battle'},{trigger:'on_trick_loss',action:'gain_shield',value:3,duration:'battle'}])});
test('더블다운은 이번 세트 3승에서 쇼다운 위력 +6으로 유지한다',()=>{assert.deepEqual(Migration.BY_ID.double.proposedEffects,[{trigger:'on_showdown_score',action:'showdown_power',value:6,condition:'set_wins_at_least',conditionValue:3,duration:'set'}])});
test('정공법은 먼저 쌓은 순수 카드가 있을 때 +3, 무첨가는 순수 슬롯 적재 후 승리 시 칩 +2를 사용한다',()=>{assert.deepEqual(Migration.BY_ID.pureboost.proposedEffects,[{trigger:'on_play',action:'increase_next_trick_rank',value:3,condition:'pure_card_in_showdown',duration:'trick'}]);assert.equal(Migration.BY_ID.clean.proposedEffects[0].condition,'pure_card_in_showdown');assert.equal(Migration.BY_ID.clean.proposedEffects[0].value,2)});
test('마이그레이션 요약은 P 기준 12장 활성화와 차단 0장을 보고한다',()=>{const summary=Migration.summary();assert.equal(summary.supportStage,'7.5-P');assert.equal(summary.activationStage,'7.5-P');assert.equal(summary.active,12);assert.equal(summary.blocked,0);assert.equal(summary.engineSupported,12)});
